name: portal-backoffice-caddy

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    environment:
      APP_DOMAIN: ${APP_DOMAIN:-:80}
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

networks:
  app:
    name: portal-backoffice-prod_default
    external: true

volumes:
  caddy_data:
  caddy_config:
